import fs from "fs";
import path from "path";

const main = async () => {
  const basePath = path.resolve(__dirname + "/../../prompts/");
  const objEntries = fs.readdirSync(basePath)
    .map((file) => {
      const key = file.split(".")[0];
      const content = fs.readFileSync(path.resolve(basePath, file), "utf-8");
      return `  ${key}: ${JSON.stringify(content)}`;
    })
    .join(',\n');

  const code = [
    "// This file is auto-generated by src/tools/prompt.ts and Do not be edited manually.",
    `export const prompts = {\n${objEntries}\n};`,
  ].join("\n");
  
  fs.writeFileSync(path.resolve(__dirname + "/../../src/agents/prompts_data.ts"), code, "utf8");
};

main();
