import fs from "fs";
import path from "path";

const main = async () => {
  const basePath = path.resolve(__dirname + "/../../prompts/");
  const ret: Record<string, string> = {};
  fs.readdirSync(basePath).map((file) => {
    const key = file.split(".")[0];
    const content = fs.readFileSync(path.resolve(basePath) + "/" + file, "utf-8");
    ret[key] = content;
  });
  
  const objEntries = Object.entries(ret)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)}`)
    .join(',\n');

  const code = [
    "// This file is auto-generated by src/tools/prompt.ts and Do not be edited manually.",
    `export const prompts = {\n${objEntries}\n};`,
  ].join("\n");
  
  fs.writeFileSync(path.resolve(__dirname + "/../../src/agents/prompts_data.ts"), code, "utf8");
};

main();
